version: '3.9'

services:
  db:
    container_name: mysql
    image: mysql:8.0.28
    ports:
      - 13306:3306
    env_file:
      - ./db/db-access.env
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/test_table.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql/
    restart: always
  api:
    container_name: spring
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 18080:8080
    env_file:
      - ./api/db-access.env
    tty: true
    volumes:
      - ./api:/workspace
    depends_on:
      - db
volumes:
  db-data: