spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL} # envから読み込む
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
  sql:
    init:
      mode: never
logging:
  level:
    root: INFO
  file:
    name: logs/app.log
mybatis:
  mapper-locations: classpath:/com/example/motocatalog/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true